packages:
    - packages/*
    - extension/*

onlyBuiltDependencies:
    - "@vscode/vsce-sign"
    - esbuild
    - keytar
    - nx

catalogs:
    default:
        "@codingame/monaco-vscode-editor-api": "26.1.1"
        "@codingame/monaco-vscode-extension-api": "26.1.1"
        "@codingame/monaco-vscode-api": "26.1.1"
        "@codingame/monaco-vscode-extensions-service-override": "26.1.1"
        "@codingame/monaco-vscode-files-service-override": "26.1.1"
        "@codingame/monaco-vscode-textmate-service-override": "26.1.1"
        "@codingame/monaco-vscode-languages-service-override": "26.1.1"
        "@codingame/monaco-vscode-theme-service-override": "26.1.1"
